# Generated by Django 5.1.5 on 2025-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(verbose_name='порядковый номер')),
                ('name', models.CharField(max_length=200, verbose_name='наименование')),
                ('category', models.IntegerField(choices=[(1, 'сервисы ДП Карагандинской области'), (2, 'сервисы государственных органов')], verbose_name='категория')),
                ('image', models.ImageField(upload_to='logotypes/', verbose_name='логотип')),
                ('target', models.URLField(verbose_name='ссылка')),
            ],
            options={
                'verbose_name': 'сервис',
                'verbose_name_plural': 'сервисы',
                'ordering': ['order_num'],
            },
        ),
    ]
