# Generated by Django 5.1.5 on 2025-01-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('date_of_create', models.DateField(verbose_name='дата создания')),
                ('file', models.FileField(upload_to='statfiles/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'стат.отчет',
                'verbose_name_plural': 'стат.отчеты',
                'ordering': ['title'],
            },
        ),
    ]
