# Generated by Django 5.1.5 on 2025-02-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text_ru', models.CharField(blank=True, max_length=500, null=True, verbose_name='текст цитаты (на русском языке)')),
                ('quote_text_kk', models.CharField(blank=True, max_length=500, null=True, verbose_name='текст цитаты (на казахском языке)')),
                ('quote_author_ru', models.CharField(blank=True, max_length=200, null=True, verbose_name='автор цитаты (на русском языке)')),
                ('quote_author_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='автор цитаты (на казахском языке)')),
                ('weather', models.JSONField(blank=True, null=True, verbose_name='Данные о погоде (json формат)')),
            ],
            options={
                'verbose_name': 'Настройки веб-сайта',
                'verbose_name_plural': 'Настройки веб-сайта',
            },
        ),
    ]
