# Generated by Django 5.1.5 on 2025-02-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='weather',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные о погоде (json формат)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quote_author_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='автор цитаты (на казахском языке)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quote_author_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='автор цитаты (на русском языке)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quote_text_kk',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='текст цитаты (на казахском языке)'),
        ),
        migrations.AlterField(
            model_name='config',
            name='quote_text_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='текст цитаты (на русском языке)'),
        ),
    ]
