# Generated by Django 5.1.5 on 2025-01-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order_num'], 'verbose_name': 'подразделение', 'verbose_name_plural': 'подразделения'},
        ),
        migrations.AlterModelOptions(
            name='management',
            options={'ordering': ['order_num'], 'verbose_name': 'служба', 'verbose_name_plural': 'службы'},
        ),
        migrations.AddField(
            model_name='department',
            name='order_num',
            field=models.PositiveIntegerField(default=1, verbose_name='порядковый номер'),
        ),
        migrations.AddField(
            model_name='management',
            name='order_num',
            field=models.PositiveIntegerField(default=1, verbose_name='порядковый номер'),
        ),
    ]
