# Generated by Django 5.1.5 on 2025-01-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_department_options_alter_management_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='рабочий телефон'),
        ),
    ]
