# Generated by Django 5.1.5 on 2025-01-19 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0004_alter_customuser_options_customuser_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.PositiveIntegerField(default=1, verbose_name='порядковый номер')),
                ('name_ru', models.CharField(max_length=250, verbose_name='наименование (на русском языке)')),
                ('name_kk', models.CharField(max_length=250, verbose_name='наименование (на казахском языке)')),
            ],
            options={
                'verbose_name': 'отдел(группа)',
                'verbose_name_plural': 'отделы(группы)',
                'ordering': ['order_num'],
            },
        ),
        migrations.AlterField(
            model_name='customuser',
            name='division',
            field=models.ForeignKey(blank=True, max_length=200, null=True, on_delete=django.db.models.deletion.RESTRICT, to='auths.division', verbose_name='отдел/группа'),
        ),
    ]
